spring.application.name=gestione-ordini-restclient
server.port=${SERVER_PORT:8080}
server.servlet.context-path=/${CONTEXT_PATH:api}

# Datasource (DB)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# REST URLs
api.gestione-pagamenti.url=${PAGAMENTO_URL:http://localhost:8081/api}
api.auth.url=${AUTH_URL:http://localhost:8083/api}

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=${RABBITMQ_RETRY_MAX_ATTEMPTS:10}
spring.rabbitmq.listener.simple.retry.initial-interval=${RABBITMQ_RETRY_INITIAL_INTERVAL:2000}s
spring.rabbitmq.listener.simple.retry.multiplier=${RABBITMQ_RETRY_MULTIPLIER:1.1}

# Mail
spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging
log.root.level=${LOG_ROOT_LEVEL:-INFO}

# Reports
reports.template.directory=${REPORTS_TEMPLATE_DIR}
reports.template.filename=${REPORTS_TEMPLATE_FILENAME}
s3.bucket.name=${BUCKET_S3_NAME}
s3.bucket.prefixes.root=${BUCKET_ROOT_PREFIX}
features.s3.receipt-upload-enabled=true